/* AUTH */
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_CHECK_SUCCESS = "AUTH_CHECK_SUCCESS";
export const AUTH_CHECK_FAILURE = "AUTH_CHECK_FAILURE";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const RUN_CODE = 'RUN_CODE';
export const RUN_CODE_SUCCESS = 'RUN_CODE_SUCCESS';
export const RUN_CODE_FAILURE = 'RUN_CODE_FAILURE';

export const SAVE_CODE = 'SAVE_CODE';
export const SAVE_CODE_SUCCESS = 'SAVE_CODE_SUCCESS';
export const SAVE_CODE_FAILURE = 'SAVE_CODE_FAILURE';

export const GET_CODE = 'GET_CODE';
export const GET_CODE_SUCCESS = 'GET_CODE_SUCCESS';
export const GET_CODE_FAILURE = 'GET_CODE_FAILURE';

export const REMOVE_CODE = 'REMOVE_CODE';
export const REMOVE_CODE_SUCCESS = 'REMOVE_CODE_SUCCESS';
export const REMOVE_CODE_FAILURE = 'REMOVE_CODE_FAILURE';
